# SPDX-License-Identifier: MIT
name: "Build hugo site and rsync to destination"
author: "Oluf Lorenzen <ol+forgejo-action@oluflorenzen.de>"
description: |
  Builds a hugo site and rsyncs the generated files somewhere.

  See README.md for details.

inputs:
  hugo_cachedir:
    description: Where to point HUGO_CACHEDIR to; should not be changed to allow caching in CI
    default: "/tmp/hugo_cache"
  hugo_args:
    description: arguments to 'hugo build'
    default: "--minify"
  main_domain:
    description: domain used in hugo baseURL for main branch builds
  pr_domain:
    description: domain used in Hugo baseURL for PR build
  pr_subdomain:
    description: subdomain used in Hugo baseURL for PR builds, will be suffixed with pr_basedomain
  main_rsync_destination_dir:
    description: rsync destination directory
  pr_rsync_destination_basedir:
    description: rsync destination directory for PR builds, will be suffixed by '/pr_basedomain', needs trailing slash
    required: false
  main_rsync_server:
    description: server name used for rsync destination
  pr_rsync_server:
    description: server name used for rsync destination for PR build; defaults to 'main_rsync_server'
    required: false
  main_rsync_user:
    description: username for the rsync destination
  pr_rsync_user:
    description: username for the rsync destination for PR build, defaults to 'main_rsync_user'
    required: false
  main_rsync_rsh:
    description: Value for 'RSYNC_RSH', e.g. 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    required: false
    default: "ssh"
  pr_rsync_rsh:
    description: Value for 'RSYNC_RSH' for PR builds; defaults to 'main_rsync_rsh'
    required: false
    default: "ssh"
  main_rsync_args:
    description: additional rsync arguments, e.g. '--dry-run'
    default: -atv --progress --delete
  pr_rsync_args:
    description: additional rsync arguments for PR build; defaults to 'main_rsync_args'
    required: false
  ssh_known_hosts:
    description: content of ssh UserKnownHostsFile, used by rsync; generate by running 'ssh-keyscan hostname'
  ssh_secret_key:
    description: SSH key for rsync
  forgejo_curl_source:
    description: where do download the script
    default: "https://git.h.oluflorenzen.de/mirrors/forgejo-curl/raw/branch/main/forgejo-curl.sh"

outputs:
  site_url:
    description: "URL to the website build"
    value: "${{ steps.build.outputs.site_url }}"

runs:
  using: "composite"
  steps:
    - name: Install required packages
      run: |
        echo "::group::Installting required packages"
        apk add  curl bash openssh-client rsync tar zstd
        echo "::endgroup::"
      shell: sh

    - name: Restore Hugo resources
      uses: actions/cache/restore@v4.2.4
      with:
        path: ./resources
        key: cache-hugo-resources-
        restore-keys: |
          cache-hugo-resources-

    - name: Restore HUGO_CACHEDIR
      uses: actions/cache/restore@v4.2.4
      with:
        path: ${{ inputs.hugo_cachedir }}
        key: hugocachedir-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          hugocachedir-${{ runner.os }}-

    - id: set_vars
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Setting variables"
        HUGO_ARGS="${{ inputs.hugo_args }}"
        RSYNC_ARGS="${{ inputs.main_rsync_args }}"
        RSYNC_ARGS_PR="${{ inputs.pr_rsync_args }}"
        RSYNC_SERVER="${{ inputs.main_rsync_server }}"
        RSYNC_SERVER_PR="${{ inputs.pr_rsync_server }}"
        RSYNC_USER="${{ inputs.main_rsync_user }}"
        RSYNC_USER_PR="${{ inputs.pr_rsync_user }}"
        RSYNC_RSH="${{ inputs.main_rsync_rsh }}"
        RSYNC_RSH_PR="${{ inputs.pr_rsync_rsh }}"
        RSYNC_DST_BASEDIR="${{ inputs.main_rsync_destination_dir }}"
        RSYNC_DST_BASEDIR_PR="${{ inputs.pr_rsync_destination_dir }}"

        HUGO_DOMAIN="${{ inputs.main_domain }}"
        RSYNC_DEST_DIR="${{ inputs.main_rsync_destination_dir }}"

        if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]; then
          echo "Pull request or non-main branch, setting *_PR variables"
          if [ ! -z "${RSYNC_ARGS_PR+x}" ] ; then RSYNC_ARGS=${RSYNC_ARGS_PR} ; fi
          if [ ! -z "${RSYNC_SERVER_PR+x}" ] ; then RSYNC_SERVER=${RSYNC_SERVER_PR} ; fi
          if [ ! -z "${RSYNC_USER_PR+x}" ] ; then RSYNC_USER=${RSYNC_USER_PR} ; fi
          if [ ! -z "${RSYNC_RSH_PR+x}" ] ; then RSYNC_RSH=${RSYNC_RSH_PR} ; fi
          HUGO_DOMAIN="${{ inputs.pr_subdomain }}-pr-${{ github.event.number }}.${{ inputs.pr_domain }}"
          RSYNC_DEST_DIR="${{ inputs.pr_rsync_destination_basedir }}${HUGO_DOMAIN}"
        fi
        for var in HUGO_ARGS RSYNC_ARGS RSYNC_SERVER RSYNC_USER RSYNC_RSH HUGO_DOMAIN RSYNC_DEST_DIR; do
          echo "${var}=${!var}"
          echo ${var}=${!var} >> ${GITHUB_ENV}
        done
        echo "::endgroup::"

    - id: build
      name: Build
      shell: bash

      run: |
        set -euo pipefail
        echo "${{ steps.set_vars.outputs }}"
        if [ "${GITHUB_EVENT_NAME}" == "pull_request" ] ; then
          _PROTO=http
        else
          _PROTO=https
        fi
        export HUGO_BASEURL="${_PROTO}://${HUGO_DOMAIN}"

        echo "::group::Running hugo build ${HUGO_ARGS}"
        echo "::notice::base URL is ${HUGO_BASEURL}"
        echo -e '### Hugo build output\n\n```' > $GITHUB_STEP_SUMMARY
        hugo build ${HUGO_ARGS} | tee -a ${GITHUB_STEP_SUMMARY}
        echo -e '\n```' >> $GITHUB_STEP_SUMMARY

        echo HUGO_BASEURL="${HUGO_BASEURL}" >> ${GITHUB_ENV}
        echo "site_url=${HUGO_BASEURL}" >> $GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Save Hugo resources
      uses: actions/cache/save@v4.2.4
      with:
        path: ./resources
        key: cache-hugo-resources-${{ hashFiles('./resources/**/*') }}

    - name: Save HUGO_CACHEDIR
      uses: actions/cache/save@v4.2.4
      with:
        path: ${{ inputs.hugo_cachedir }}
        key: hugocachedir-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

    - id: deploy
      name: Deploy with rsync
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && chmod -R g=,o= ~/.ssh
        echo "${{ inputs.ssh_known_hosts }}" > ~/.ssh/known_hosts
        if ! grep -q "${RSYNC_SERVER}" ~/.ssh/known_hosts; then echo "::error::${RSYNC_SERVER} is not in ~/.ssh/known_hosts" ; exit 1 ; fi

        eval $(ssh-agent -s)
        echo '${{ inputs.ssh_secret_key }}' | ssh-add -

        echo "::group::Running rsync"
        _rsync_exit=0
        echo -e '### Rsync output\n\n```' > $GITHUB_STEP_SUMMARY
        set -x
        rsync ${RSYNC_ARGS} ./public/* "${RSYNC_USER}@${RSYNC_SERVER}:${RSYNC_DEST_DIR}" || _rsync_exit=$? | tee -a $GITHUB_STEP_SUMMARY
        set +x
        echo -e '\n```\n\n' >> $GITHUB_STEP_SUMMARY
        if [ ! ${_rsync_exit} == 0 ]; then
          echo "::warning::rsync failed with code ${_rsync_exit}, running again with 'RSYNC_RSH={RSYNC_RSH} -v'"
          echo -e '### Rsync output with RSYNC_RSH appended with -v\n\n```' >> $GITHUB_STEP_SUMMARY
          RSYNC_RSH="${RSYNC_RSH} -v" rsync ${RSYNC_ARGS} ./public/* "${RSYNC_USER}@${RSYNC_SERVER}:${RSYNC_DEST_DIR}" | tee -a $GITHUB_STEP_SUMMARY
          echo -e '\n```' >> $GITHUB_STEP_SUMMARY
          echo "::error::rsync failed with ${_rsync_exit}"
          exit ${_rsync_exit}
        fi
        echo "::endgroup::"

    - name: Link to website, add PR comment
      shell: bash
      run: |
        set -euo pipefail
        echo "::notice::Build is accessible at ${{ steps.build.outputs.site_url }}" | tee -a $GITHUB_STEP_SUMMARY

        if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]; then
          echo "This is a PR, adding a comment if it hasnt been created yet"
          echo "::group::Creating comment on PR"
          curl --fail -sS -o /usr/local/bin/forgejo-curl.sh ${{ inputs.forgejo_curl_source }} && chmod +x /usr/local/bin/forgejo-curl.sh
          export PATH=/usr/local/bin:$PATH
          forgejo-curl.sh --token "${{ env.FORGEJO_TOKEN }}" login ${{ env.FORGEJO_SERVER_URL }}
          forgejo-curl.sh api_json ${{ env.FORGEJO_SERVER_URL }}/api/v1/user
          if forgejo-curl.sh --verbose api ${{ env.FORGEJO_SERVER_URL }}/api/v1/repos/${{ env.FORGEJO_REPOSITORY }}/issues/${{ github.event.number }}/comments | grep -q "Website preview" ; then
            echo "Comment already created"
          else
            forgejo-curl.sh --verbose api_json --data-raw '{"body":"Website preview: ${{ env.HUGO_BASEURL }}"}' ${{ env.FORGEJO_SERVER_URL }}/api/v1/repos/${{ env.FORGEJO_REPOSITORY }}/issues/${{ github.event.number }}/comments
          fi
          echo "::endgroup::"
        fi
branding:
  icon: "check"
  color: "blue"
