from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_package_bump_hooks = []
post_package_bump_hooks = []
pre_bump_hooks = []
post_bump_hooks = [
    "git push",
    "git push --tags",
]

[changelog]
path = "CHANGELOG.md"
authors = []
template = "remote"
remote = "https://git.h.oluflorenzen.de"
repository = "action-hugo-build-rsync"
owner = "finkregh"

[packages.ci]
path = ".forgejo/workflows"
public_api = false

[packages.cog-release-changelog]
path = "actions/cog-release-changelog"

[packages.hugo-build-rsync]
path = "actions/hugo-build-rsync"

[packages.install-jo]
path = "actions/install-jo"

[packages.prettier-markdown]
path = "actions/prettier-markdown"

[packages.release-with-cog]
path = "actions/release-with-cog"
