# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Prettier + Markdownlint"
author: "Oluf Lorenzen <ol+forgejo-action@oluflorenzen.de"
description: Prettier + Markdownlint + push changes

inputs:
  prettier_plugins:
    description: 'Additional prettier plugins to install, space-separated, e.g. "prettier-plugin-toml prettier-plugin-sh prettier-plugin-merge"'
    required: false
    default: "prettier-plugin-toml prettier-plugin-sh prettier-plugin-merge"

runs:
  using: "composite"
  #runs-on: ubuntu-latest
  steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
      id: extract_branch

    - name: Checkout
      id: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
        ref: ${{ steps.extract_branch.outputs.branch }}

    - name: install prettier-plugins
      shell: bash
      # workaround for <https://github.com/creyD/prettier_action/issues/111>
      run: |
        echo "::group::Install prettier plugins"
        npm install prettier --save-dev
        # shellcheck disable=SC2157
        if [ -z "${{ inputs.prettier_plugins }}" ]; then
          echo "No additional prettier plugins specified."
        else
          echo "Installing additional prettier plugins: ${{ inputs.prettier_plugins }}"
          # shellcheck disable=SC2043
          for plugin in ${{ inputs.prettier_plugins }}; do
            echo "Installing plugin: $plugin"
            npm install "$plugin" --save-dev
          done
        fi
        echo "::endgroup::"

    - name: Prettier
      #uses: https://github.com/creyD/prettier_action@v4.6
      uses: https://github.com/creyD/prettier_action@dev
      with:
        prettier_plugins: "prettier-plugin-toml"
        allow_other_plugins: true
        no_commit: true
        add_options: "--update"
        prettier_options: --write .

    - name: Markdownlint
      uses: https://github.com/DavidAnson/markdownlint-cli2-action@v20
      continue-on-error: true
      with:
        fix: true
        globs: "**/*.md"

    - name: Git diff and status
      shell: sh
      run: |
        echo "::group::Git diff and status"
        git -c color.ui=always status; git -c color.ui=always diff
        echo "::endgroup::"

    - name: Commit and push linting fixes
      # Run only on:
      # - Pull requests
      # - Not on the default branch
      #if: >
      #  github.event_name == 'pull_request' &&
      #  github.ref_name != github.event.repository.default_branch
      uses: https://github.com/stefanzweifel/git-auto-commit-action@v6.0.1
      with:
        branch: ${{ steps.extract_branch.outputs.branch }}
        commit_message: "chore: changes from ci"
        commit_user_name: ci-linting
        add_options: "--update"
        # file_pattern: "*"
        # skip_dirty_check: true
        status_options: "--untracked-files=no"

    - name: Markdownlint (blocking)
      uses: https://github.com/DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: "**/*.md"
