name: linting

on:
  [push, workflow_dispatch]
  #pull_request:
  #  types: [opened, synchronize, reopened]
  #push:
  #  branches:
  #    - main
  #workflow_dispatch:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: install prettier-plugins
        # workaround for <https://github.com/creyD/prettier_action/issues/111>
        run: npm install prettier prettier-plugin-toml prettier-plugin-sh --save-dev

      - name: Prettier
        #uses: https://github.com/creyD/prettier_action@v4.6
        uses: https://github.com/Finkregh/prettier_action@3c2ef7889ea1c94462bf8ceaf50fe2b0c6421f8e
        with:
          prettier_plugins: "prettier-plugin-toml prettier-plugin-sh"
          allow_other_plugins: true
          no_commit: true
          add_options: "--update"
          prettier_options: --write .

      - name: Markdownlint
        uses: https://github.com/DavidAnson/markdownlint-cli2-action@v20
        continue-on-error: true
        with:
          fix: true
          globs: "**/*.md"

      - name: Git status, diff
        run: git -c color.ui=always status; git -c color.ui=always diff

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests OR
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' ||
          github.ref_name != github.event.repository.default_branch
        uses: https://github.com/stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          commit_message: "chore: changes from ci"
          commit_user_name: ci-linting
          add_options: "--update"
          status_options: "--untracked-files=no"

      - name: Markdownlint (blocking)
        uses: https://github.com/DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"
