name: lint

on:
  workflow_dispatch:
  #[push, workflow_dispatch]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Markdown and prettier
        uses: ./actions/prettier-markdown
