name: linting

on:
  [push, workflow_dispatch]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Prettier and Markdownlint
        uses: ./action-prettier-markdownlint
